import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';
import { doctorRoutes } from './routes/doctors.routes';
import { errorMiddleware } from '../../shared/middleware/error.middleware';
import { logger } from '../../shared/utils/logger';
dotenv.config();
const app = express();
const PORT = process.env.DOCTOR_PORT || 3009;
app.use(helmet()); app.use(cors({ origin: process.env.FRONTEND_URL, credentials: true })); app.use(express.json());
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'doctor-service' }));
app.use('/api/doctors', doctorRoutes);
app.use('/api/consultations', doctorRoutes);
app.use(errorMiddleware);
app.listen(PORT, () => logger.info(`Doctor service running on port ${PORT}`));
export default app;
